name: 기능 이슈 템플릿
description: 기능을 개발할 때, 기능에 대한 이슈를 작성합니다.
title: "[Task] "
labels: ["✨ feature"]
body:
  - type: textarea
    id: feature
    attributes:
      label: 어떤 기능인가요?
      description: 추가하려는 기능에 대해 간결하게 설명해주세요

  - type: textarea
    id: tasks
    attributes:
      label: 작업 상세 내용
      value: |
        - [ ] TODO
        - [ ] TODO
        - [ ] TODO

  - type: textarea
    id: references
    attributes:
      label: 참고할만한 자료(선택)
